//
//  TransactionPresenter.swift
//  test
//
//  Created by Daniel Salhuana on 4/6/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionPresentationLogic {
    func presentError(response: Transaction.Error.Response)
    func presentLoaded(response: Transaction.CurrencyLoad.Response)
}

class TransactionPresenter: TransactionPresentationLogic {
    weak var viewController: TransactionDisplayLogic?
    
    func presentError(response: Transaction.Error.Response) {
        switch response.errorType {
        case .emptyCurrency:
            break
        case .noLocalCurrency:
            break
        case .notDollarCurrency:
            break
        case .notLoad:
            break
        }
    }
    
    func presentLoaded(response: Transaction.CurrencyLoad.Response) {
        let source = response.source
        let target = response.target
        let buyRate = source.buyRate.getMoneyValue(symbol: source.symbol)
        let sellRate = source.sellRate.getMoneyValue(symbol: source.symbol)
        let viewModel = Transaction.CurrencyLoad.ViewModel(sourceSymbol: source.symbol, sourceName: source.currencyName, targetSymbol: target.symbol, targetName: target.currencyName, buyRate: buyRate, sellRate: sellRate)
        viewController?.displayCurrencyLoaded(viewModel: viewModel)
    }
}
