//
//  TransactionModels.swift
//  test
//
//  Created by Daniel Salhuana on 4/6/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Transaction {
    enum CurrencyLoad {
        struct Request {
        }
        struct Response {
            let source: Currency
            let target: Currency
        }
        struct ViewModel {
            let transactionViewModel: TransactionViewModel
        }
    }
    
    enum AmountChange {
        struct Request {
            let amountValue: Double?
        }
        struct Response {
            let amountChanged: Double
        }
        struct ViewModel {
            let amountChanged: String
        }
    }
    
    enum CurrencyChange {
        enum CurrencyOption {
            case source
            case target
        }
        
        struct Request {
            let option: CurrencyOption
        }
    }
    
    enum Error {
        enum ErrorType {
            case notLoad
            case emptyCurrency
            case noLocalCurrency
            case notDollarCurrency
        }
        struct Response {
            let errorType: ErrorType
        }
        struct ViewModel {
            let message: String
        }
    }
}
