//
//  TransactionModels.swift
//  test
//
//  Created by Daniel Salhuana on 4/6/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Transaction {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum CurrencyLoad {
        struct Request {
        }
        struct Response {
            let source: Currency
            let target: Currency
        }
        struct ViewModel {
            let sourceSymbol: String
            let sourceName: String
            let targetSymbol: String
            let targetName: String
            let buyRate: String
            let sellRate: String
        }
    }
    
    enum Error {
        enum ErrorType {
            case notLoad
            case emptyCurrency
            case noLocalCurrency
            case notDollarCurrency
        }
        
        struct Response {
            let errorType: ErrorType
        }
        struct ViewModel {
            let message: String
        }
    }
}
