//
//  TransactionInteractor.swift
//  test
//
//  Created by Daniel Salhuana on 4/6/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TransactionBusinessLogic {
    func doLoadCurrencies(request: Transaction.CurrencyLoad.Request)
    func docChangeAmount(request: Transaction.AmountChange.Request)
    func doChangeCurrency(request: Transaction.CurrencyChange.Request)
}

protocol TransactionDataStore {
    var currencies: [Currency] { get set }
    var currencyToUpdate: Transaction.CurrencyChange.CurrencyOption? { get set }
}

class TransactionInteractor: TransactionBusinessLogic, TransactionDataStore {
    
    var presenter: TransactionPresentationLogic?
    var worker: TransactionWorker? = TransactionWorker()
    var currencies = [Currency]()
    var currencyToUpdate: Transaction.CurrencyChange.CurrencyOption?
    
    private let isoSoles = "PEN"
    private let isoDollar = "USD"
    private var source: Currency? = nil
    private var target: Currency? = nil
    
    func doLoadCurrencies(request: Transaction.CurrencyLoad.Request) {
        worker?.doGetConversionRate(completionHandler: {[weak self] (data) in
            guard let data = data, let welf = self else {
                //LLAMAR PRESENTER ERROR
                return
            }
            welf.currencies = welf.worker?.doParseConversionRates(data: data) ?? []
            validateCurrencies()
        })
    }
    
    private func validateCurrencies() {
        guard let source = getCurrencyByIso(currencies: currencies, iso: isoSoles), let target = getCurrencyByIso(currencies: currencies, iso: isoDollar) else {
            //LLAMAR PRESENTER ERROR
            return
        }
        self.source = source
        self.target = target
        let response = Transaction.CurrencyLoad.Response(source: source, target: target)
        presenter?.presentLoaded(response: response)
    }
    
    private func getCurrencyByIso(currencies: [Currency], iso: String) -> Currency? {
        return currencies.first { (currency) -> Bool in
            return currency.iso == iso
        }
    }
    
    func docChangeAmount(request: Transaction.AmountChange.Request) {
        guard let target = target, let source = source, let currencyValue = request.amountValue else {
            return
        }
        let dollarAmount = source.buyRate * currencyValue
        let newAmount = target.sellRate * dollarAmount
        let response = Transaction.AmountChange.Response(amountChanged: newAmount)
        presenter?.presentAccountChanged(response: response)
    }
    
    func doChangeCurrency(request: Transaction.CurrencyChange.Request) {
        self.currencyToUpdate = request.option
    }
}
