//
//  TransactionPresenterTests.swift
//  test
//
//  Created by Daniel Salhuana on 4/7/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import test
import XCTest

class TransactionPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: TransactionPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupTransactionPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupTransactionPresenter() {
        sut = TransactionPresenter()
    }
    
    // MARK: Test doubles
    
    class TransactionDisplayLogicSpy: TransactionDisplayLogic {
        func displayCurrencyLoaded(viewModel: Transaction.CurrencyLoad.ViewModel) {
            
        }
        
        func displayAccountChanged(viewModel: Transaction.AmountChange.ViewModel) {
            
        }
        
        func displayErrorView(viewModel: Transaction.Error.ViewModel) {
            
        }
        
//        var displaySomethingCalled = false
//
//        func displaySomething(viewModel: Transaction.Something.ViewModel) {
//            displaySomethingCalled = true
//        }
    }
    
    // MARK: Tests
    
//    func testPresentSomething() {
//        // Given
//        let spy = TransactionDisplayLogicSpy()
//        sut.viewController = spy
//        let response = Transaction.Something.Response()
//        
//        // When
//        sut.presentSomething(response: response)
//        
//        // Then
//        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//    }
}
