//
//  TransactionWorkerTests.swift
//  test
//
//  Created by Daniel Salhuana on 4/7/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import test
import XCTest

class TransactionWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: TransactionWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupTransactionWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupTransactionWorker() {
        sut = TransactionWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
