//
//  CurrenciesModels.swift
//  test
//
//  Created by Daniel Salhuana on 4/7/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Currencies {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum LoadCurrency {
        struct Request {
        }
        struct Response {
            var currencies: [Currency]
        }
        struct ViewModel {
            var currencies: [CurrencyViewModel]
        }
    }
}
