//
//  CurrenciesRouter.swift
//  test
//
//  Created by Daniel Salhuana on 4/7/20.
//  Copyright (c) 2020 Daniel Salhuana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrenciesRoutingLogic {
    func routeToTransactionView()
}

protocol CurrenciesDataPassing {
  var dataStore: CurrenciesDataStore? { get }
}

class CurrenciesRouter: NSObject, CurrenciesRoutingLogic, CurrenciesDataPassing {
  weak var viewController: CurrenciesViewController?
  var dataStore: CurrenciesDataStore?
  
  // MARK: Routing
    
    func routeToTransactionView() {
        if let viewController = viewController {
            let navCon = viewController.navigationController
            let transactionViewController = navCon?.viewControllers.first(where: { (controller) -> Bool in
                return controller is TransactionViewController
            })
            if let transactionViewController = transactionViewController as? TransactionViewController, var destinationStore = transactionViewController.router?.dataStore {
                passDataToTransactionController(source: dataStore, destination: &destinationStore)
            }
            navCon?.popViewController(animated: true)
        }
    }
  
  // MARK: Passing data
  
    func passDataToTransactionController(source: CurrenciesDataStore?, destination: inout TransactionDataStore) {
        destination.currencySelected = source?.currencySelected
    }
    
  //func passDataToSomewhere(source: CurrenciesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
